services:
  resumemaker:
    image: ghcr.io/lildengzi/resumemaker:latest
    container_name: resumemaker
    restart: unless-stopped
    ports:
      - "8501:8501"
    environment:
      RESUMEMAKER_CONFIG_PATH: /app/ResumeMaker/data/config.json
    env_file:
      - path: .env
        required: false
    volumes:
      - ./data:/app/ResumeMaker/data
